spring:
  datasource:
    url: jdbc:postgresql://dpg-d3hh3qb3fgac739q64ng-a.virginia-postgres.render.com:5432/artemanha
    username: artemanha_user
    password: rshuFSDbFwjYZgj2oNgnyHTIFFke1HFy
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8080
